repos:
  - repo: https://github.com/ssciwr/clang-format-hook
    rev: v16.0.2
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|h|hh|hpp|hxx)$
        args: ["--style=file", "-i"]

  - repo: local
    hooks:
      - id: cppcheck-server
        name: cppcheck (server)
        language: system
        pass_filenames: false
        entry: cppcheck
        args:
          - server/
          - --enable=warning,style,performance,portability
          - --std=c++20
          - --suppress=ctuOneDefinitionRuleViolation

      - id: cppcheck-client
        name: cppcheck (client)
        language: system
        pass_filenames: false
        entry: cppcheck
        args:
          - client/
          - --enable=warning,style,performance,portability
          - --std=c++20
          - --suppress=ctuOneDefinitionRuleViolation
