name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: |
        pip3 install pre-commit
        sudo apt-get -y install cppcheck
        pre-commit install
        pre-commit run --all-files
