name: test-events
on:
  pull_request:
  push:
jobs:
  test-events-client-to-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          mkdir build
          cd build && cmake -DEVENTS=ON .. && make
          cd ..
          git clone https://github.com/eldipa/tiburoncin.git
          cd tiburoncin
          make
          sudo cp tiburoncin /usr/bin/
          cd ..
          sudo apt-get install valgrind
          ./tests/events/client_to_server/run_tests.sh build/ tests/events/client_to_server/cases/ single-client no-valgrind 60 10
          ./tests/events/client_to_server/compare_outputs.sh tests/events/client_to_server/cases/ tests/events/client_to_server/expected/
          rm -r build
  test-events-server-to-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          mkdir build
          cd build && cmake -DEVENTS=ON .. && make
          cd ..
          git clone https://github.com/eldipa/tiburoncin.git
          cd tiburoncin
          make
          sudo cp tiburoncin /usr/bin/
          cd ..
          sudo apt-get install valgrind
          ./tests/events/server_to_client/run_tests.sh build/ tests/events/server_to_client/cases/ single-client no-valgrind 60 10
          ./tests/events/server_to_client/compare_outputs.sh tests/events/server_to_client/cases/ tests/events/server_to_client/expected/
          rm -r build
