name: test-prod
on:
  pull_request:
  push:
jobs:
  test-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-ttf: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
      - run: |
          ./build.sh
